spring:
  application:
    name: spring-cloud-consumer
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8002/eureka/,http://peer3:8003/eureka/

feign:
  hystrix:
    # 开启断路器
    enabled: true
