server:
  port: 8001

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#服务的名称
spring:
  application:
    name: product-service
  #指定从哪个配置中心读取
  cloud:
    config:
      discovery:
        service-id: config-server-jdbc
        enabled: true
      profile: dev
      label: dev
name_server: 127.0.0.1:9876
order_topic: order_topic